### ISSUE TITLE
Maven Central Release?

### ISSUE THREAD

**Issue by ChristianMurphy** [UW-Madison-DoIT/KeyValueStore#26]
Hey @UW-Madison-DoIT/uportal-home-committers! :wave: 

Excited to see efforts toward moving making it easier to adopt uPortal-home.
https://groups.google.com/a/apereo.org/d/msg/uportal-dev/hK-kXquF1hE/lA-ppvkvBQAJ
https://github.com/Jasig/uPortal-start/pull/84

As part of the uPortal-home setup process it appears key value store is required:
https://groups.google.com/a/apereo.org/d/msg/uportal-dev/DAX1Uk7iJGE/QiBZJNXyAgAJ

However when scanning maven central for a released version I am unable to find one:
https://search.maven.org/#search%7Cga%7C1%7Cedu.wisc.my
https://search.maven.org/#search%7Cga%7C1%7Ckey-value-store

Am I looking in the wrong place?

**Comment by vertein** [comment]
Not looking in the wrong place, there is no good reason for this not to be in central.  I'll work on this.  I'll try to do this, this afternoon.

**Comment by vertein** [comment]
PR to change distribution - https://github.com/UW-Madison-DoIT/KeyValueStore/pull/27

**Comment by vertein** [comment]
Now that PR is merged, I'm going to go ahead and cut a release.

**Comment by vertein** [comment]
3.1.1 has been released to maven central and project is set to release to maven central in the future.  Thanks for bringing this up.

```
<groupId>edu.wisc.my.apps</groupId>
<artifactId>key-value-store</artifactId>
```

**Comment by ChristianMurphy** [comment]
Thanks @vertein! :bow:
